run:
  timeout: 120s
issues:
  exclude-dirs:
    - generated/
linters:
  enable:
    - gofmt
    - goimports
    - govet
    - revive
    - ineffassign
    - goconst
    - gosimple
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - dogsled
    - goprintffuncname
    - misspell
    - prealloc
    - stylecheck
    - unconvert
    - gocritic
  disable-all: true
linters-settings:
  goconst:
    min-len: 4
    min-occurrences: 4
  revive:
    rules:
      - name: unused-parameter
        disabled: true
      - name: superfluous-else
        disabled: true
      - name: dot-imports
        disabled: true
