run:
  deadline: 120s
  skip-dirs:
    - generated/
          # minimal length of string constant, 3 by default
linters:
  enable:
    - gofmt
    - goimports
    - govet
    - golint
    - ineffassign
    - goconst
    - deadcode
    - gofmt
    - goimports
    - gosimple
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - dogsled
    - goprintffuncname
    - misspell
    - prealloc
    - scopelint
    - stylecheck
    - unconvert
    - gocritic
  disable-all: true
linters-settings:
  goconst:
    min-len: 4
    min-occurrences: 4
